# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/rufus/Git/UnrealEngine
GAMEPROJECTFILE =/home/rufus/Documents/Unreal Projects/SPD_Spel1/SPD_Spel1.uproject

TARGETS = \
	SPD_Spel1-Linux-Debug  \
	SPD_Spel1-Linux-DebugGame  \
	SPD_Spel1-Linux-Test  \
	SPD_Spel1-Linux-Shipping  \
	SPD_Spel1 \
	SPD_Spel1Editor-Linux-Debug  \
	SPD_Spel1Editor-Linux-DebugGame  \
	SPD_Spel1Editor-Linux-Test  \
	SPD_Spel1Editor-Linux-Shipping  \
	SPD_Spel1Editor \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Test  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Test  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Test  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Test  \
	UnrealServer-Linux-Shipping  \
	UnrealServer\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend SPD_Spel1Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug SPD_Spel1Editor-Linux-Debug


SPD_Spel1-Linux-Debug:
	 $(PROJECTBUILD) SPD_Spel1 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SPD_Spel1-Linux-DebugGame:
	 $(PROJECTBUILD) SPD_Spel1 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SPD_Spel1-Linux-Test:
	 $(PROJECTBUILD) SPD_Spel1 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SPD_Spel1-Linux-Shipping:
	 $(PROJECTBUILD) SPD_Spel1 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SPD_Spel1:
	 $(PROJECTBUILD) SPD_Spel1 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SPD_Spel1Editor-Linux-Debug:
	 $(PROJECTBUILD) SPD_Spel1Editor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SPD_Spel1Editor-Linux-DebugGame:
	 $(PROJECTBUILD) SPD_Spel1Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SPD_Spel1Editor-Linux-Test:
	 $(PROJECTBUILD) SPD_Spel1Editor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SPD_Spel1Editor-Linux-Shipping:
	 $(PROJECTBUILD) SPD_Spel1Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SPD_Spel1Editor:
	 $(PROJECTBUILD) SPD_Spel1Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
